### ISSUE TITLE
SerialPort cannot enter listening

### ISSUE THREAD

**Issue by HughWick** [java-native/jssc#116] opened 2021-09-10 06:33 UTC
I was able to correctly access the listen event method after opening the serial port using the following code
```java
  var serialPort = new SerialPort("COM3"); 
  serialPort.openPort();
  serialPort.setParams(19200, DATA_BITS, STOP_BITS, PARITY);
  System.out.println("---->>" + serialPort);
  int mask = SerialPort.MASK_RXCHAR + SerialPort.MASK_CTS + SerialPort.MASK_DSR;
  serialPort.setEventsMask(mask);
  serialPort.addEventListener(new PortListener(serialPort, textPane, actionBO));
```
However, when I close the serial port, then unplug the USB cable from the serial port and plug it back in, I can't access the listen events (the code above prints statements to see if it's a different serialPort).
```java
 serialPort.closePort();
```
When I got desperate, I found I could open the serial port with a putty connection, receive the data, close the serial port, then come back and access the listening event again with the code above ......
```java
public class PortListener implements SerialPortEventListener{
  @Override
    public void serialEvent(SerialPortEvent serialPortEvent) {
      System.out.println("=====Entering the listen====");
       .........
  }
}
```

PS:
 As long as I don't unplug the USB I can access the listener events every time, but as soon as I unplug it once the above problem occurs, even if I restart the java service it doesn't recover, I have to connect the serial port once with putty and then the java will resume accessing the listener events.

What am I doing wrong?

**Comment by pietrygamat** [comment] 2021-09-24 21:25
I am investigating potential relation of this to #107. Could you share the code that shows the use of `serialPort` inside `new PortListener(serialPort, textPane, actionBO)` when the problem is triggered? 

I am also interested in the squencing of the events: 
- is the `serialPort.closePort()` always executed before unplugging the cable? 
- do you catch or ignore any exceptions when closing the port or when reopenning it after reconnecting the device? 
- do you call `serialPort.open()` on the same instance of serialPort or after re-attaching the adapter do you create a `new SerialPort("COM3");` and add to it a new PortListener?
- are you on Windows and jssc 2.9.4?

**Comment by HughWick** [comment] 2021-09-27 02:22
> I am investigating potential relation of this to #107. Could you share the code that shows the use of `serialPort` inside `new PortListener(serialPort, textPane, actionBO)` when the problem is triggered?
> 
> I am also interested in the squencing of the events:
> 
> * is the `serialPort.closePort()` always executed before unplugging the cable?
> * do you catch or ignore any exceptions when closing the port or when reopenning it after reconnecting the device?
> * do you call `serialPort.open()` on the same instance of serialPort or after re-attaching the adapter do you create a `new SerialPort("COM3");` and add to it a new PortListener?
> 
> Also, are you on Windows and jssc 2.9.4?

Sorry, I forgot to mention that I was using version 2.9.3, I upgraded to 2.9.4 and the problem did not reappear, thanks for your contribution, thanks brother

**Comment by pietrygamat** [comment] 2021-09-27 07:15
Perfect.

**Closed by pietrygamat** 2021-09-27 07:15 UTC
